services:
  - type: web
    name: freefire-diamonds-app
    env: node
    buildCommand: |
      npm install
      npm install -g pm2
    startCommand: pm2 start ecosystem.config.js --env production
    preDeployCommand: ""  # Si no necesitas hacer nada antes del deploy
    plan: free
    regions:
      - oregon
